### ISSUE TITLE
Tiny error when validating HTML 5

### ISSUE THREAD

**Issue by willbprog127** [joewing/www#1]
Hi Joe,

Not trying to nit-pick at all -- just telling you about an HTML5 validation error on the JWM config page (http://www.joewing.net/projects/jwm/config.shtml).  If any of my pages weren't validating, I'd totally want to know, but anyway...

The validator (and the Dillo browser) say this:

`HTML warning: line 117, Unexpected closing tag: </li> -- expected </ul>.`

Although I've looked at line 117, I can't seem to find where the issue is.  

Again, just letting you know so you can once again have 100 percent perfect validation! :smile:

**Comment by joewing** [comment]
That should be fixed now. Thanks for letting me know!
